import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import AppProvider from "@/components/AppProvider";
import { PaymentSheet } from "@/components/pricing/PaymentSheet";
import { PageTransition } from "@/components/PageTransition";
const sans = Manrope({
  variable: "--font-sans",
  subsets: ["latin"],
});

const serif = Inter({
  variable: "--font-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sans.variable} ${serif.variable} font-sans antialiased`}
      >
        <AppProvider>
          {children}
          <Toaster />
          <PaymentSheet />
        </AppProvider>
      </body>
    </html>
  );
}
